apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-service
  template:
    metadata:
      labels:
        app: template-service
    spec:
      containers:
      - name: template-service
        image: ghcr.io/impit-mpit/template-service-master:latest
        ports:
        - containerPort: 3001
          name: grpc
        env:
        - name: DATABASE_HOST
          value: "10.0.0.9"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_DB
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: db_name
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: db_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: db_password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: template-service
spec:
  selector:
    app: template-service
  ports:
  - port: 3001
    targetPort: 3001
    name: grpc