apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- virtual-service.yaml
- config.yaml
- deployment.yaml
images:
- name: ghcr.io/impit-mpit/tag-service-master
  newTag: 754d50d
