apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: template-service
spec:
  hosts:
  - template-service
  http:
  - match:
    - uri:
        prefix: /template.templateService
    route:
    - destination:
        host: template-service
        port:
          number: 3001