
name: Docker Image CI

on:
  workflow_dispatch:
#   push:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT        
      - name: Build
        uses: docker/build-push-action@v5
        with:
          load: true
          push: false
          tags: ghcr.io/impit-mpit/news-service-${{ github.ref_name }}:${{ steps.vars.outputs.sha_short }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/impit-mpit/news-service-${{ github.ref_name }}:${{ steps.vars.outputs.sha_short }}
      - name: Install Kustomize
        run: |
              curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
              sudo mv kustomize /usr/local/bin/
    
      - name: Update Kustomize image tag
        run: |
              cd k8s
              kustomize edit set image ghcr.io/impit-mpit/news-service-${{ github.ref_name }}:${{ steps.vars.outputs.sha_short }}
              
      - name: Commit and push changes
        run: |
              git config --global user.name 'GitHub Actions'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              git add k8s/
              git commit -m "Update image tag to ${{ steps.vars.outputs.sha_short }}"
              git push  